"""saved dashboard filters

A clinic's own named views of the dashboard's lists -- "Bugungi Telegram
qabullari", "Javobsiz lidlar". Each of those used to be a developer's job:
a query parameter, a control, a deploy. The clinic knows which questions it
asks its data every morning and should not have to ask for them one at a
time.

The filter is JSONB rather than columns because the part that varies is
exactly the part worth storing: appointments filter by day and status,
leads by status, conversations by whether a human took over. Columns for
the union would be mostly NULL and would need a migration every time a list
gains a control -- which is the cost this table exists to remove.

Nothing here is executed. What is stored is a set of query parameters for
endpoints that already exist, validated against an allow-list in
app.api.admin.filters before it is written, so a saved view is replayed by
the same API a person clicking the controls uses.

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "527feaadcded"
down_revision: str | Sequence[str] | None = "a7f1c93be204"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "saved_filters",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("resource", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name=op.f("fk_saved_filters_tenant_id_tenants")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_saved_filters")),
        sa.UniqueConstraint("tenant_id", "resource", "name", name="uq_saved_filters_name"),
    )
    op.create_index(
        op.f("ix_saved_filters_tenant_id"), "saved_filters", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_saved_filters_tenant_id"), table_name="saved_filters")
    op.drop_table("saved_filters")
    # ### end Alembic commands ###
